worker_processes auto;

mail {
    server_name smtp.thestablefoundation.org;

    proxy_pass_error_message on;

    ssl                 on;
    ssl_certificate     /etc/letsencrypt/live/smtp.thestablefoundation.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/smtp.thestablefoundation.org/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;

    server {
        listen     25;
        protocol   smtp;
        smtp_auth  login plain cram-md5;
    }

    server {
        listen    110;
        protocol  pop3;
        pop3_auth plain apop cram-md5;
    }

    server {
        listen   143;
        protocol imap;
    }
}
